import type { DocumentTemplate } from "./types";

export const STARTER_TEMPLATES: DocumentTemplate[] = [
  {
    id: "ft-proposal",
    name: "Project Proposal",
    description: "Standard client proposal with scope, timeline, and pricing",
    icon: "◆",
    category: "proposals",
    blocks: [
      { type: "h1", content: "Project Proposal" },
      { type: "paragraph", content: "Thank you for the opportunity to work together. Below is a summary of scope, deliverables, and investment." },
      { type: "h2", content: "Objective" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "Scope of Work" },
      { type: "bullet", content: "" },
      { type: "bullet", content: "" },
      { type: "bullet", content: "" },
      { type: "bullet", content: "" },
      { type: "h2", content: "Timeline" },
      { type: "todo", content: "Phase 1 — Discovery", checked: false },
      { type: "todo", content: "Phase 2 — Design", checked: false },
      { type: "todo", content: "Phase 3 — Execution", checked: false },
      { type: "todo", content: "Phase 4 — Delivery", checked: false },
      { type: "h2", content: "Investment" },
      { type: "table", content: "", tableData: { rows: [["Phase", "Deliverable", "Cost"], ["", "", ""], ["", "", ""], ["", "Total", ""]] } },
      { type: "h2", content: "Terms" },
      { type: "bullet", content: "50% deposit to begin, 50% on delivery" },
      { type: "bullet", content: "2 rounds of revisions included per phase" },
      { type: "bullet", content: "Additional revisions billed at hourly rate" },
      { type: "divider", content: "" },
      { type: "paragraph", content: "Looking forward to creating something great together." },
    ],
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
    usageCount: 0,
    lastUsed: null,
    source: "felmark",
  },
  {
    id: "ft-meeting",
    name: "Meeting Notes",
    description: "Structured meeting notes with agenda, discussion, and action items",
    icon: "☰",
    category: "notes",
    blocks: [
      { type: "h2", content: "Meeting Notes" },
      { type: "callout", content: "Date: — · Attendees: — · Duration: —" },
      { type: "h3", content: "Agenda" },
      { type: "numbered", content: "" },
      { type: "numbered", content: "" },
      { type: "numbered", content: "" },
      { type: "h3", content: "Discussion" },
      { type: "paragraph", content: "" },
      { type: "h3", content: "Action Items" },
      { type: "todo", content: "", checked: false },
      { type: "todo", content: "", checked: false },
      { type: "todo", content: "", checked: false },
      { type: "h3", content: "Next Meeting" },
      { type: "paragraph", content: "" },
    ],
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
    usageCount: 0,
    lastUsed: null,
    source: "felmark",
  },
  {
    id: "ft-onboarding",
    name: "Client Onboarding",
    description: "Welcome doc for new clients with setup checklist",
    icon: "→",
    category: "onboarding",
    blocks: [
      { type: "h1", content: "Welcome" },
      { type: "callout", content: "Everything you need to get started working together." },
      { type: "h2", content: "About Us" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "How We Work" },
      { type: "bullet", content: "Communication: " },
      { type: "bullet", content: "Meetings: " },
      { type: "bullet", content: "Deliverables: " },
      { type: "h2", content: "What We Need From You" },
      { type: "todo", content: "Brand assets (logos, fonts, colors)", checked: false },
      { type: "todo", content: "Access credentials", checked: false },
      { type: "todo", content: "Point of contact", checked: false },
      { type: "h2", content: "Next Steps" },
      { type: "numbered", content: "Kick-off call" },
      { type: "numbered", content: "Review first deliverable" },
      { type: "numbered", content: "Feedback round" },
    ],
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
    usageCount: 0,
    lastUsed: null,
    source: "felmark",
  },
  {
    id: "ft-agreement",
    name: "Service Agreement",
    description: "Freelance service contract with standard terms",
    icon: "§",
    category: "contracts",
    blocks: [
      { type: "h1", content: "Service Agreement" },
      { type: "paragraph", content: "This agreement is entered into between [Provider] and [Client]." },
      { type: "h2", content: "1. Scope of Services" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "2. Compensation" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "3. Timeline" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "4. Revisions" },
      { type: "paragraph", content: "Two (2) rounds of revisions are included per deliverable." },
      { type: "h2", content: "5. Ownership & IP" },
      { type: "paragraph", content: "Upon full payment, all deliverables and intellectual property transfer to Client." },
      { type: "h2", content: "6. Termination" },
      { type: "paragraph", content: "Either party may terminate with 14 days written notice." },
      { type: "divider", content: "" },
      { type: "paragraph", content: "Provider: _____________________ Date: _________" },
      { type: "paragraph", content: "Client: _______________________ Date: _________" },
    ],
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
    usageCount: 0,
    lastUsed: null,
    source: "felmark",
  },
  {
    id: "ft-weekly",
    name: "Weekly Report",
    description: "End-of-week summary with progress, blockers, and next week plan",
    icon: "◎",
    category: "planning",
    blocks: [
      { type: "h2", content: "Weekly Report" },
      { type: "callout", content: "Week of — " },
      { type: "h3", content: "Completed This Week" },
      { type: "todo", content: "", checked: true },
      { type: "todo", content: "", checked: true },
      { type: "todo", content: "", checked: true },
      { type: "h3", content: "In Progress" },
      { type: "todo", content: "", checked: false },
      { type: "todo", content: "", checked: false },
      { type: "h3", content: "Blockers" },
      { type: "paragraph", content: "" },
      { type: "h3", content: "Next Week" },
      { type: "todo", content: "", checked: false },
      { type: "todo", content: "", checked: false },
      { type: "todo", content: "", checked: false },
    ],
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
    usageCount: 0,
    lastUsed: null,
    source: "felmark",
  },
  {
    id: "ft-brief",
    name: "Project Brief",
    description: "Project overview with background, objectives, and requirements",
    icon: "☐",
    category: "planning",
    blocks: [
      { type: "h1", content: "Project Brief" },
      { type: "h2", content: "Background" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "Objectives" },
      { type: "numbered", content: "" },
      { type: "numbered", content: "" },
      { type: "numbered", content: "" },
      { type: "h2", content: "Target Audience" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "Requirements" },
      { type: "h3", content: "Must Have" },
      { type: "bullet", content: "" },
      { type: "bullet", content: "" },
      { type: "h3", content: "Nice to Have" },
      { type: "bullet", content: "" },
      { type: "h2", content: "Timeline & Budget" },
      { type: "paragraph", content: "" },
      { type: "h2", content: "Success Criteria" },
      { type: "bullet", content: "" },
      { type: "bullet", content: "" },
    ],
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
    usageCount: 0,
    lastUsed: null,
    source: "felmark",
  },
];
