import { useState } from "react";
const MO=[{m:"Oct",v:4200},{m:"Nov",v:6800},{m:"Dec",v:5100},{m:"Jan",v:8400},{m:"Feb",v:11200},{m:"Mar",v:14800}];
const INVS=[{id:"INV-047",client:"Bolt Fitness",av:"B",color:"#8a7e5a",amount:4000,sent:"Mar 25",due:"Apr 1",days:4,status:"overdue",viewed:2},{id:"INV-048",client:"Meridian Studio",av:"M",color:"#6a7b8a",amount:2400,sent:"Mar 29",due:"Apr 12",days:0,status:"sent",viewed:3},{id:"INV-049",client:"Nora Kim",av:"N",color:"#9a8472",amount:3200,sent:"Mar 28",due:"Apr 11",days:0,status:"sent",viewed:0}];
const ALL_INVS=[...INVS,{id:"INV-046",client:"Meridian Studio",av:"M",color:"#6a7b8a",amount:1800,sent:"Mar 15",due:"Mar 29",days:0,status:"paid",viewed:0},{id:"INV-045",client:"Nora Kim",av:"N",color:"#9a8472",amount:2200,sent:"Mar 10",due:"Mar 24",days:0,status:"paid",viewed:0},{id:"INV-044",client:"Bolt Fitness",av:"B",color:"#8a7e5a",amount:2000,sent:"Feb 28",due:"Mar 14",days:0,status:"paid",viewed:0}];
const WEEKS=[{w:"W1",rate:100},{w:"W2",rate:110},{w:"W3",rate:110},{w:"W4",rate:120},{w:"W5",rate:110},{w:"W6",rate:110},{w:"W7",rate:110},{w:"W8",rate:108}];
const CLIENTS=[{name:"Meridian Studio",av:"M",color:"#6a7b8a",months:[2400,1800,2400,1800,2200,1800],total:12400},{name:"Nora Kim",av:"N",color:"#9a8472",months:[0,2200,0,3000,0,3000],total:8200},{name:"Bolt Fitness",av:"B",color:"#8a7e5a",months:[1800,2200,2000,0,0,0],total:6000}];
const ML=["Oct","Nov","Dec","Jan","Feb","Mar"];
function sc(s){return s==="overdue"?"var(--rs)":s==="sent"?"var(--em)":"var(--sg)"}

function Revenue(){const max=Math.max(...MO.map(m=>m.v));const[hov,setHov]=useState(null);return(<div className="mb"><div className="mb-hd"><div><div className="mb-lb">Earned This Month</div><div className="mb-rv"><span className="mb-big" style={{color:"var(--sg)"}}>$14,800</span><span className="mb-trend up">+40%</span></div><div className="mb-sub">Best month since October · $200 to goal</div></div><div className="mb-hd-r"><div className="mb-hd-s"><span className="mb-hd-sv" style={{color:"var(--rs)"}}>$9,600</span><span className="mb-hd-sl">Outstanding</span></div><div className="mb-hd-s"><span className="mb-hd-sv">$22,000</span><span className="mb-hd-sl">Pipeline</span></div></div></div>
<div className="mb-chart"><svg width="100%" height="120" viewBox="0 0 480 120" preserveAspectRatio="none"><defs><linearGradient id="rg1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--sg)" stopOpacity=".1"/><stop offset="100%" stopColor="var(--sg)" stopOpacity="0"/></linearGradient></defs>{[.25,.5,.75].map((p,i)=><line key={i} x1="0" y1={120-p*100} x2="480" y2={120-p*100} stroke="var(--bdl)" strokeWidth=".5"/>)}<path d={`M0,${120-(MO[0].v/max)*95-5} ${MO.map((m,i)=>`L${(i/(MO.length-1))*480},${120-(m.v/max)*95-5}`).join(" ")} L480,120 L0,120Z`} fill="url(#rg1)"/><polyline points={MO.map((m,i)=>`${(i/(MO.length-1))*480},${120-(m.v/max)*95-5}`).join(" ")} fill="none" stroke="var(--sg)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" opacity=".6"/>{MO.map((m,i)=>{const cx=(i/(MO.length-1))*480,cy=120-(m.v/max)*95-5;return(<g key={i} onMouseEnter={()=>setHov(i)} onMouseLeave={()=>setHov(null)} style={{cursor:"default"}}><circle cx={cx} cy={cy} r={hov===i?6:4} fill="#fff" stroke="var(--sg)" strokeWidth={hov===i?2.5:2} style={{transition:"all .12s"}}/>{hov===i&&<><rect x={cx-32} y={cy-28} width="64" height="20" rx="5" fill="var(--i9)"/><text x={cx} y={cy-15} textAnchor="middle" fill="#fff" fontSize="10" fontFamily="'JetBrains Mono',monospace" fontWeight="500">${m.v.toLocaleString()}</text></>}</g>)})}</svg><div className="mb-chart-lb">{MO.map((m,i)=><span key={i} className={hov===i?"on":""}>{m.m}</span>)}</div></div>
<div className="mb-summary">{[{lb:"Collected",v:"$14,800",c:"var(--sg)"},{lb:"Pending",v:"$5,600",c:"var(--em)"},{lb:"Overdue",v:"$4,000",c:"var(--rs)"}].map((s,i)=>(<div key={i} className="mb-sum-item"><div className="mb-sum-dot" style={{background:s.c}}/><span className="mb-sum-lb">{s.lb}</span><span className="mb-sum-val" style={{color:s.c}}>{s.v}</span></div>))}</div></div>)}

function Outstanding(){const total=INVS.reduce((s,i)=>s+i.amount,0);const overdue=INVS.filter(i=>i.status==="overdue").reduce((s,i)=>s+i.amount,0);const r=22,circ=2*Math.PI*r;return(<div className="mb"><div className="mb-hd"><div><div className="mb-lb">Outstanding</div><div className="mb-rv"><span className="mb-big" style={{color:"var(--rs)"}}>${total.toLocaleString()}</span></div><div className="mb-sub">{INVS.length} invoices · ${overdue.toLocaleString()} overdue</div></div><div className="mb-hd-ring"><svg width="56" height="56" viewBox="0 0 56 56"><circle cx="28" cy="28" r={r} fill="none" stroke="var(--bdl)" strokeWidth="5"/><circle cx="28" cy="28" r={r} fill="none" stroke="var(--rs)" strokeWidth="5" strokeDasharray={circ} strokeDashoffset={circ-(overdue/total)*circ} strokeLinecap="round" transform="rotate(-90 28 28)"/><text x="28" y="26" textAnchor="middle" dominantBaseline="central" style={{fontSize:11,fontWeight:600,fill:"var(--rs)",fontFamily:"var(--mono)"}}>{Math.round((overdue/total)*100)}%</text><text x="28" y="37" textAnchor="middle" style={{fontSize:7,fill:"var(--i3)",fontFamily:"var(--mono)"}}>overdue</text></svg></div></div>
<div className="mb-inv-list">{INVS.map(inv=>(<div key={inv.id} className={`mb-inv ${inv.status}`}><div className="mb-inv-ac" style={{background:inv.status==="overdue"?"var(--rs)":"var(--em)"}}/><div className="mb-inv-av" style={{background:inv.color}}>{inv.av}</div><div className="mb-inv-info"><div className="mb-inv-client">{inv.client}</div><div className="mb-inv-meta"><span>{inv.id}</span><span>·</span><span>Sent {inv.sent}</span>{inv.viewed>0&&<><span>·</span><span style={{color:"var(--lv)"}}>Viewed {inv.viewed}×</span></>}</div></div><div className="mb-inv-right"><div className="mb-inv-amt" style={{color:inv.status==="overdue"?"var(--rs)":"var(--i8)"}}>${inv.amount.toLocaleString()}</div>{inv.status==="overdue"?<span className="mb-inv-badge overdue">{inv.days}d overdue</span>:<span className="mb-inv-badge sent">Due {inv.due}</span>}</div></div>))}</div>
<div className="mb-timeline"><div className="mb-tl-lb">Payment Timeline</div><div className="mb-tl-bar"><div className="mb-tl-seg" style={{width:`${(overdue/total)*100}%`,background:"var(--rs)",opacity:.5}}/><div className="mb-tl-seg" style={{width:`${((total-overdue)/total)*100}%`,background:"var(--em)",opacity:.3}}/></div><div className="mb-tl-labels"><span style={{color:"var(--rs)"}}>${overdue.toLocaleString()} overdue</span><span style={{color:"var(--em)"}}>${(total-overdue).toLocaleString()} pending</span></div></div></div>)}

function Invoices(){const[f,setF]=useState("all");const filtered=f==="all"?ALL_INVS:ALL_INVS.filter(i=>i.status===f);const counts={all:ALL_INVS.length,overdue:ALL_INVS.filter(i=>i.status==="overdue").length,sent:ALL_INVS.filter(i=>i.status==="sent").length,paid:ALL_INVS.filter(i=>i.status==="paid").length};return(<div className="mb"><div className="mb-hd"><div><div className="mb-lb">Invoices</div><div className="mb-sub">{ALL_INVS.length} total · ${ALL_INVS.reduce((s,i)=>s+i.amount,0).toLocaleString()}</div></div><button className="mb-new-btn">+ New Invoice</button></div>
<div className="mb-filters">{[{id:"all",lb:"All"},{id:"overdue",lb:"Overdue"},{id:"sent",lb:"Sent"},{id:"paid",lb:"Paid"}].map(ft=>(<button key={ft.id} className={`mb-fil${f===ft.id?" on":""}`} onClick={()=>setF(ft.id)}>{ft.lb}<span className="mb-fil-n">{counts[ft.id]}</span></button>))}</div>
<div className="mb-tbl"><div className="mb-tbl-hd"><span className="mb-th" style={{flex:1}}>Client</span><span className="mb-th w70">Invoice</span><span className="mb-th w60">Date</span><span className="mb-th w80 right">Amount</span><span className="mb-th w70 right">Status</span></div>{filtered.map(inv=>(<div key={inv.id} className="mb-tbl-row"><div className="mb-tbl-client"><div className="mb-tbl-av" style={{background:inv.color}}>{inv.av}</div><span>{inv.client}</span></div><span className="mb-tbl-cell w70">{inv.id}</span><span className="mb-tbl-cell w60">{inv.sent}</span><span className="mb-tbl-cell w80 right" style={{fontWeight:500,color:inv.status==="overdue"?"var(--rs)":"var(--i8)"}}>${inv.amount.toLocaleString()}</span><span className="w70 right"><span className="mb-tbl-status" style={{color:sc(inv.status),background:sc(inv.status).replace(")",",0.05)").replace("var(","rgba(").replace("--rs","180,110,94").replace("--em","168,116,68").replace("--sg","94,143,94")}}>{inv.status}</span></span></div>))}</div></div>)}

function Rate(){const target=150;const maxR=Math.max(target,...WEEKS.map(w=>w.rate))+20;const[hov,setHov]=useState(null);return(<div className="mb"><div className="mb-hd"><div><div className="mb-lb">Effective Rate</div><div className="mb-rv"><span className="mb-big" style={{color:"var(--lv)"}}>$108<span className="mb-big-u">/hr</span></span></div><div className="mb-sub">Target: $150/hr · 72% there</div></div><div className="mb-hd-r"><div className="mb-hd-s"><span className="mb-hd-sv">215h</span><span className="mb-hd-sl">This month</span></div><div className="mb-hd-s"><span className="mb-hd-sv">$23.2k</span><span className="mb-hd-sl">Total billed</span></div></div></div>
<div className="mb-chart"><svg width="100%" height="100" viewBox="0 0 480 100" preserveAspectRatio="none"><line x1="0" y1={100-(target/maxR)*85} x2="480" y2={100-(target/maxR)*85} stroke="var(--sg)" strokeWidth="1" strokeDasharray="6 4" opacity=".3"/><text x="475" y={100-(target/maxR)*85-4} textAnchor="end" fontSize="8" fill="var(--sg)" fontFamily="'JetBrains Mono',monospace" opacity=".5">$150 target</text><defs><linearGradient id="rg2" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--lv)" stopOpacity=".08"/><stop offset="100%" stopColor="var(--lv)" stopOpacity="0"/></linearGradient></defs><path d={`M0,${100-(WEEKS[0].rate/maxR)*85} ${WEEKS.map((w,i)=>`L${(i/(WEEKS.length-1))*480},${100-(w.rate/maxR)*85}`).join(" ")} L480,100 L0,100Z`} fill="url(#rg2)"/><polyline points={WEEKS.map((w,i)=>`${(i/(WEEKS.length-1))*480},${100-(w.rate/maxR)*85}`).join(" ")} fill="none" stroke="var(--lv)" strokeWidth="2" strokeLinecap="round" opacity=".5"/>{WEEKS.map((w,i)=>{const cx=(i/(WEEKS.length-1))*480,cy=100-(w.rate/maxR)*85;return(<g key={i} onMouseEnter={()=>setHov(i)} onMouseLeave={()=>setHov(null)} style={{cursor:"default"}}><circle cx={cx} cy={cy} r={hov===i?5:3} fill="#fff" stroke="var(--lv)" strokeWidth={hov===i?2:1.5}/>{hov===i&&<><rect x={cx-28} y={cy-26} width="56" height="18" rx="4" fill="var(--i9)"/><text x={cx} y={cy-14} textAnchor="middle" fill="#fff" fontSize="9" fontFamily="'JetBrains Mono',monospace">${w.rate}/hr</text></>}</g>)})}</svg><div className="mb-chart-lb">{WEEKS.map((w,i)=><span key={i} className={hov===i?"on":""}>{w.w}</span>)}</div></div>
<div className="mb-rate-clients"><div className="mb-sec-lb">By Client</div>{[{name:"Meridian Studio",rate:120,hours:64,color:"#6a7b8a"},{name:"Nora Kim",rate:106,hours:42,color:"#9a8472"},{name:"Bolt Fitness",rate:95,hours:62,color:"#8a7e5a"}].map((c,i)=>(<div key={i} className="mb-rate-row"><div className="mb-rate-av" style={{background:c.color}}>{c.name[0]}</div><div className="mb-rate-info"><div className="mb-rate-name">{c.name}</div><div className="mb-rate-bar"><div style={{width:`${(c.rate/target)*100}%`,background:c.rate>=target?"var(--sg)":c.rate>=100?"var(--lv)":"var(--rs)"}}/></div></div><div className="mb-rate-vals"><span className="mb-rate-v" style={{color:c.rate>=target?"var(--sg)":c.rate>=100?"var(--lv)":"var(--rs)"}}>${c.rate}/hr</span><span className="mb-rate-h">{c.hours}h</span></div></div>))}</div></div>)}

function RevChart(){const gt=CLIENTS.reduce((s,c)=>s+c.total,0);const mt=ML.map((_,mi)=>CLIENTS.reduce((s,c)=>s+c.months[mi],0));const maxM=Math.max(...mt);const[hov,setHov]=useState(null);return(<div className="mb"><div className="mb-hd"><div><div className="mb-lb">Revenue Breakdown</div><div className="mb-rv"><span className="mb-big" style={{color:"var(--i8)"}}>${(gt/1000).toFixed(1)}k</span><span className="mb-sub-il">total earned</span></div><div className="mb-sub">Last 6 months · {CLIENTS.length} clients</div></div></div>
<div className="mb-stacked">{ML.map((m,mi)=>(<div key={mi} className="mb-st-col"><div className="mb-st-bars">{CLIENTS.map((c,ci)=>{const h=maxM>0?(c.months[mi]/maxM)*100:0;return h>0?<div key={ci} className="mb-st-seg" style={{height:`${h}%`,background:c.color,opacity:hov===null||hov===ci?.45:.1}} onMouseEnter={()=>setHov(ci)} onMouseLeave={()=>setHov(null)}/>:null})}</div><span className="mb-st-lb">{m}</span><span className="mb-st-val">${(mt[mi]/1000).toFixed(1)}k</span></div>))}</div>
<div className="mb-bd"><div className="mb-sec-lb">By Client</div>{CLIENTS.map((c,i)=>(<div key={i} className={`mb-bd-row${hov===i?" hov":""}`} onMouseEnter={()=>setHov(i)} onMouseLeave={()=>setHov(null)}><div className="mb-bd-av" style={{background:c.color}}>{c.av}</div><div className="mb-bd-info"><div className="mb-bd-name">{c.name}</div><div className="mb-bd-bar"><div style={{width:`${(c.total/gt)*100}%`,background:c.color,opacity:.4}}/></div></div><div className="mb-bd-vals"><span className="mb-bd-val">${(c.total/1000).toFixed(1)}k</span><span className="mb-bd-pct">{Math.round((c.total/gt)*100)}%</span></div></div>))}</div></div>)}

export default function MoneyBlocks(){return(<><link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700;1,9..144,400;1,9..144,500&family=DM+Sans:ital,wght@0,300;0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@300;400;500&display=swap" rel="stylesheet"/>
<style>{`
*{box-sizing:border-box;margin:0;padding:0}:root{--bg:#edeae5;--card:#fff;--tint:#f8f7f4;--bd:#ddd9d2;--bdl:#ebe8e2;--i9:#252320;--i8:#363330;--i7:#4a4743;--i6:#5e5b56;--i5:#7a7772;--i4:#9b988f;--i3:#b5b2a9;--i2:#d0cdc6;--em:#a87444;--embg:rgba(168,116,68,.04);--sg:#5e8f5e;--sgbg:rgba(94,143,94,.04);--lv:#7d7db0;--lvbg:rgba(125,125,176,.03);--rs:#b46e5e;--rsbg:rgba(180,110,94,.04);--mono:'JetBrains Mono',monospace}
.pg{font-family:'DM Sans',sans-serif;background:var(--bg);min-height:100vh;padding:48px 24px 80px}.pg-in{max-width:640px;margin:0 auto}
.pg-hd{margin-bottom:36px}.pg-eye{font-family:var(--mono);font-size:10px;color:var(--em);text-transform:uppercase;letter-spacing:.14em;margin-bottom:6px}
.pg-t{font-family:'Fraunces',serif;font-size:36px;font-weight:600;color:var(--i9);margin-bottom:6px}.pg-t em{font-style:italic;color:var(--sg)}
.pg-sub{font-size:15px;color:var(--i4);line-height:1.6}
.pg-lb{font-family:var(--mono);font-size:9px;color:var(--i3);text-transform:uppercase;letter-spacing:.06em;margin:32px 0 10px 2px;display:flex;align-items:center;gap:8px}.pg-lb::after{content:'';flex:1;height:1px;background:var(--bdl)}
.mb{background:var(--card);border:1px solid var(--bd);border-radius:20px;overflow:hidden;transition:all .18s cubic-bezier(.16,1,.3,1);margin-bottom:16px}.mb:hover{transform:translateY(-2px);box-shadow:0 12px 40px rgba(0,0,0,.04)}
.mb-hd{padding:22px 26px 16px;display:flex;align-items:flex-start;justify-content:space-between;border-bottom:1px solid var(--bdl)}
.mb-lb{font-family:var(--mono);font-size:9px;color:var(--i3);text-transform:uppercase;letter-spacing:.08em}
.mb-rv{display:flex;align-items:baseline;gap:8px;margin-top:6px}
.mb-big{font-family:'Fraunces',serif;font-size:32px;font-weight:700;line-height:1}.mb-big-u{font-size:16px;font-weight:400;opacity:.4}
.mb-sub{font-size:12px;color:var(--i4);margin-top:4px}.mb-sub-il{font-size:14px;color:var(--i4);margin-left:2px}
.mb-trend{font-family:var(--mono);font-size:11px;padding:3px 10px;border-radius:6px}.mb-trend.up{color:var(--sg);background:var(--sgbg);border:1px solid rgba(94,143,94,.06)}
.mb-hd-r{display:flex;gap:16px;text-align:right}.mb-hd-s{}.mb-hd-sv{font-family:var(--mono);font-size:15px;font-weight:500;color:var(--i7);display:block}.mb-hd-sl{font-family:var(--mono);font-size:8px;color:var(--i3);text-transform:uppercase;margin-top:1px;display:block}
.mb-hd-ring{flex-shrink:0}
.mb-new-btn{padding:8px 18px;border-radius:9px;border:1px solid var(--bd);background:var(--card);font-size:12px;font-family:inherit;color:var(--i5);cursor:pointer;font-weight:500;transition:all .1s}.mb-new-btn:hover{background:var(--tint);transform:translateY(-1px)}
.mb-chart{padding:16px 26px 8px}.mb-chart-lb{display:flex;justify-content:space-between;font-family:var(--mono);font-size:9px;color:var(--i3);padding:4px 0 0}.mb-chart-lb .on{color:var(--i7);font-weight:500}
.mb-sec-lb{font-family:var(--mono);font-size:8px;color:var(--i3);text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px}
.mb-summary{display:flex;padding:14px 26px;border-top:1px solid var(--bdl)}
.mb-sum-item{flex:1;display:flex;align-items:center;gap:8px;padding:0 8px}.mb-sum-item:not(:last-child){border-right:1px solid var(--bdl)}
.mb-sum-dot{width:6px;height:6px;border-radius:2px;flex-shrink:0}.mb-sum-lb{font-size:12px;color:var(--i4);flex:1}.mb-sum-val{font-family:var(--mono);font-size:13px;font-weight:500;flex-shrink:0}
.mb-inv-list{padding:12px 18px}
.mb-inv{display:flex;align-items:center;gap:12px;padding:14px 12px;border:1px solid var(--bdl);border-radius:14px;margin-bottom:8px;transition:all .1s;position:relative;overflow:hidden}.mb-inv:hover{border-color:var(--i2);box-shadow:0 4px 14px rgba(0,0,0,.02)}
.mb-inv.overdue{padding-left:16px}.mb-inv:not(.overdue){padding-left:12px}
.mb-inv-ac{width:4px;position:absolute;left:0;top:0;bottom:0;border-radius:4px 0 0 4px}
.mb-inv-av{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:15px;font-weight:600;color:var(--card);flex-shrink:0}
.mb-inv-info{flex:1;min-width:0}.mb-inv-client{font-size:14px;font-weight:500;color:var(--i7)}.mb-inv-meta{display:flex;align-items:center;gap:4px;font-family:var(--mono);font-size:10px;color:var(--i3);margin-top:2px}
.mb-inv-right{flex-shrink:0;text-align:right}.mb-inv-amt{font-family:'Fraunces',serif;font-size:20px;font-weight:600;line-height:1}
.mb-inv-badge{font-family:var(--mono);font-size:9px;font-weight:500;padding:2px 8px;border-radius:5px;display:inline-block;margin-top:3px}
.mb-inv-badge.overdue{color:var(--rs);background:var(--rsbg);border:1px solid rgba(180,110,94,.06)}
.mb-inv-badge.sent{color:var(--em);background:var(--embg);border:1px solid rgba(168,116,68,.06)}
.mb-timeline{padding:14px 26px 18px;border-top:1px solid var(--bdl)}
.mb-tl-lb{font-family:var(--mono);font-size:8px;color:var(--i3);text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px}
.mb-tl-bar{display:flex;height:6px;border-radius:3px;overflow:hidden;gap:2px}.mb-tl-seg{height:100%;border-radius:3px}
.mb-tl-labels{display:flex;justify-content:space-between;font-family:var(--mono);font-size:9px;margin-top:6px}
.mb-filters{display:flex;gap:3px;padding:12px 26px;border-bottom:1px solid var(--bdl)}
.mb-fil{padding:6px 14px;border-radius:8px;border:1px solid var(--bd);background:var(--card);font-size:12px;font-family:inherit;color:var(--i5);cursor:pointer;display:flex;align-items:center;gap:4px;font-weight:500;transition:all .1s}.mb-fil:hover{background:var(--tint)}.mb-fil.on{background:var(--i9);color:var(--card);border-color:var(--i9)}
.mb-fil-n{font-family:var(--mono);font-size:9px;opacity:.5}
.mb-tbl{padding:0 26px 18px}.mb-tbl-hd{display:flex;align-items:center;padding:10px 0;border-bottom:1px solid var(--bdl)}
.mb-th{font-family:var(--mono);font-size:9px;color:var(--i3);text-transform:uppercase;letter-spacing:.05em}
.mb-tbl-row{display:flex;align-items:center;padding:12px 0;border-bottom:1px solid var(--bdl);transition:background .06s;border-radius:6px}.mb-tbl-row:hover{background:var(--tint)}
.mb-tbl-client{flex:1;display:flex;align-items:center;gap:10px;font-size:14px;color:var(--i7);font-weight:500}
.mb-tbl-av{width:28px;height:28px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;color:var(--card);flex-shrink:0}
.mb-tbl-cell{font-family:var(--mono);font-size:11px;color:var(--i4)}
.mb-tbl-status{font-family:var(--mono);font-size:9px;font-weight:500;padding:3px 10px;border-radius:6px}
.w60{width:60px}.w70{width:70px}.w80{width:80px}.right{text-align:right}
.mb-rate-clients{padding:14px 26px 18px;border-top:1px solid var(--bdl)}
.mb-rate-row{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--bdl)}.mb-rate-row:last-child{border-bottom:none}
.mb-rate-av{width:32px;height:32px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:600;color:var(--card);flex-shrink:0}
.mb-rate-info{flex:1;min-width:0}.mb-rate-name{font-size:13px;color:var(--i6);margin-bottom:4px}
.mb-rate-bar{height:4px;background:var(--bdl);border-radius:2px;overflow:hidden}.mb-rate-bar div{height:100%;border-radius:2px;transition:width .4s ease}
.mb-rate-vals{flex-shrink:0;text-align:right}.mb-rate-v{font-family:var(--mono);font-size:14px;font-weight:500;display:block}.mb-rate-h{font-family:var(--mono);font-size:10px;color:var(--i3);display:block;margin-top:1px}
.mb-stacked{display:flex;gap:6px;padding:16px 26px 8px;height:140px;align-items:flex-end}
.mb-st-col{flex:1;display:flex;flex-direction:column;align-items:center;height:100%}
.mb-st-bars{flex:1;width:100%;display:flex;flex-direction:column-reverse;gap:2px;border-radius:4px 4px 0 0;overflow:hidden}
.mb-st-seg{width:100%;border-radius:2px;transition:opacity .15s,height .4s ease;cursor:default}
.mb-st-lb{font-family:var(--mono);font-size:9px;color:var(--i3);margin-top:4px}.mb-st-val{font-family:var(--mono);font-size:8px;color:var(--i4);margin-top:1px}
.mb-bd{padding:14px 26px 20px;border-top:1px solid var(--bdl)}
.mb-bd-row{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--bdl);transition:all .08s;border-radius:6px;cursor:default}.mb-bd-row:last-child{border-bottom:none}.mb-bd-row.hov{background:var(--tint);padding-left:6px;padding-right:6px}
.mb-bd-av{width:32px;height:32px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:600;color:var(--card);flex-shrink:0}
.mb-bd-info{flex:1;min-width:0}.mb-bd-name{font-size:14px;font-weight:500;color:var(--i7);margin-bottom:4px}
.mb-bd-bar{height:5px;background:var(--bdl);border-radius:3px;overflow:hidden}.mb-bd-bar div{height:100%;border-radius:3px;transition:width .4s ease}
.mb-bd-vals{flex-shrink:0;text-align:right}.mb-bd-val{font-family:var(--mono);font-size:15px;font-weight:500;color:var(--i7);display:block}.mb-bd-pct{font-family:var(--mono);font-size:10px;color:var(--i3);display:block;margin-top:1px}
`}</style>
<div className="pg"><div className="pg-in">
<div className="pg-hd"><div className="pg-eye">Space Blocks · Money</div><div className="pg-t">5 blocks that replace <em>your spreadsheet</em></div><div className="pg-sub">Each block is a complete financial tool. Hover the charts. Filter invoices. Compare rates by client.</div></div>
<div className="pg-lb">1 · Revenue Counter</div><Revenue/>
<div className="pg-lb">2 · Outstanding</div><Outstanding/>
<div className="pg-lb">3 · Invoice List</div><Invoices/>
<div className="pg-lb">4 · Rate Tracker</div><Rate/>
<div className="pg-lb">5 · Revenue Chart</div><RevChart/>
</div></div></>)}
